run_accept_tests:
    tags: [docker_runner_2]
    image: ubuntu:latest
    only:
        - pushes
    script:
        # install terraform
        - wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_freebsd_amd64.zip
        - unzip *.zip
        - export PATH=$PATH:`pwd`
        - terraform version
        
        # install go
        - wget https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
        - sudo tar -C /usr/local -xzf *.gz
        - export PATH=$PATH:/usr/local/go/bin
        - go version

        # download repo and build the provider
        - mkdir $HOME/go
        - export GOPATH=$HOME/go
        - mkdir -p $GOPATH/src/gitlab.eng.vmware.com/vapi-sdk
        - cd $GOPATH/src/gitlab.eng.vmware.com/vapi-sdk
        - git clone https://gitlab.eng.vmware.com/vapi-sdk/terraform-provider-vmc.git
        - cd $GOPATH/src/gitlab.eng.vmware.com/vapi-sdk/terraform-provider-vmc
        - go get
        - go build -o terraform-provider-vmc
        - terraform init
        - export REFRESH_TOKEN=085c5176-8c2e-4c11-ae31-0b802fce424d
        - make testacc



