run_accept_tests:
    tags: [k8-runner]
    image: vmcswaggers-docker-local.artifactory.eng.vmware.com/terraform-provider-vmc:1.0
    only: 
      - pushes
    script:
        - git config --global url."git@gitlab.eng.vmware.com:".insteadOf "https://gitlab.eng.vmware.com/"
        - git checkout $CI_COMMIT_REF_NAME
        - cp -r * $GOPATH/src/gitlab.eng.vmware.com/vapi-sdk/terraform-provider-vmc

        # build the provider
        - cd $GOPATH/src/gitlab.eng.vmware.com/vapi-sdk/terraform-provider-vmc
        - go get
        - go build -o terraform-provider-vmc
        - terraform init
        - make testacc