run_accept_tests:
    tags: [k8-runner]
    image: vmcswaggers-docker-local.artifactory.eng.vmware.com/terraform-provider-vmc:1.1
    only: 
      - pushes
    script:
        #terraform version: v0.12.12#
        #golang version: go1.12.1 linux/amd64#
        #you can find terraform-vmc-provider Dockerfile here: https://wiki.eng.vmware.com/VSphere_SDK/Implementing_Docker_containers_in_Automation_SDK%27s_Pipelines_on_GitLab#Current_Dockerfile_configuration #
        
        - git config --global url."git@gitlab.eng.vmware.com:".insteadOf "https://gitlab.eng.vmware.com/"
        - git checkout $CI_COMMIT_REF_NAME
        - cp -r * $GOPATH/src/gitlab.eng.vmware.com/vapi-sdk/terraform-provider-vmc

        # build the provider
        - cd $GOPATH/src/gitlab.eng.vmware.com/vapi-sdk/terraform-provider-vmc
        - go get
        - go build -o terraform-provider-vmc
        - terraform init
        - make testacc