name: terraform-provider-vmc
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Running acceptance test
        env:
           ORG_ID: ${{ secrets.ord_id }}
           REFRESH_TOKEN: ${{ secrets.refresh_token }}
           TEST_SDDC_ID: ${{ secrets.test_sddc_id }}
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          rm -rf $GOPATH/src/github.com/vmware/terraform-provider-vmc/*
          cp -r * $GOPATH/src/github.com/vmware/terraform-provider-vmc
          cd $GOPATH/src/github.com/vmware/terraform-provider-vmc
          #terraform-provider-linter#
          #export PATH=/home/go/bin:$PATH
          #go get github.com/bflad/tfproviderlint/cmd/tfproviderlint
          #tfproviderlint ./...
          #Run test#
          go get
          go build -o terraform-provider-vmc          
          terraform init
          make testacc
